# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Frag deinen Provider
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
     Fordere deine Daten nach DSGVO.
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://frag-deinen-provider.de" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  pefi-78

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal

exclude: ["pads"]
